apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-job
spec:
  template:
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["echo", "hello-world!!!"]
      restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-world-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: busybox
            name: busybox
            command: ["echo", "hello-world!!!"]
          restartPolicy: Never