apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    env: dev
  name: nginx-daemonset
  namespace: dev
spec:
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - image: nginx
        name: nginx    