---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: ex-infrastructure
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-infrastructure
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ex-infrastructure
  tags:
    karpenter.sh/discovery: ex-infrastructure
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["t"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t2"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["2"]
  limits:
    cpu: 500
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s